### ISSUE TITLE
Example husky configs using this library

### ISSUE THREAD

**Issue by exKAZUu** [dosentmatter/force-stdin-tty#1]
Hi, I want to use your library with husky (for commitizen on Windows), but I’m not sure how to use. Could you add some example configs for your library + husky?

**Comment by dosentmatter** [comment]
@exKAZUu, are you using a UNIX environment in Windows such as git bash, cygwin, or Windows Subsystem for Linux? Or are you using the command prompt? I don't expect it to work in the command prompt since it uses '/dev/tty'. To make it work in the command prompt, I'll need to update the package to use 'CON'.

When using my package, there is no difference in the husky config.

Your package.json can be something like this:
```
  "scripts": {
    "pre-push": "./scripts/pre-push.js",
  },
  "husky": {
    "hooks": {
      "pre-push": "yarn run pre-push"
    }
  },
```

I have an example script in the README https://github.com/dosentmatter/force-stdin-tty#usage. This would be the `./scripts/pre-push.js` script.
```
#!/usr/bin/env node
// ./scripts/pre-push.js
import { forceStdinTty } from 'force-stdin-tty';

let overwroteStdin = false;
try {
  overwroteStdin = forceStdinTty();
} catch {
  console.error('Please push your code in a terminal.');
  process.exit(1);
}

// your code to prompt for input here

if (overwroteStdin) {
  process.stdin.destroy();
}
```

Place your code to prompt for input at `// your code to prompt for input here`. Without my package to forcefully open stdin, husky normally doesn't have access to stdin, so your prompts for inputs wouldn't work even though running the script directly would work fine.
