### ISSUE TITLE
To capture input from user

### ISSUE THREAD

**Issue by pramod-designs** [dosentmatter/force-stdin-tty#2]
Hi Apologies 
in advance if you think this is not the place for this query, am new to git and node world am suppose to write a hook in node js which wants to execute a task based on user input a character y or n, I tried using ur example

I ended up getting weird errors like c:/ws/something along with some gc functions

If it's not too much can you please let me know how to do this

**Comment by dosentmatter** [comment]
Are you on windows? What is your dev environment like? How did you install node? It seems like you are on window because of `C:/` file path.

Even if you are on windows, are you using a Unix shell-like environment like [WSL](https://docs.microsoft.com/en-us/windows/wsl/faq), Cygwin, git bash, etc.?

Right now, I don't expect this to work without a Unix shell-like environment because I [assume the `/dev/tty` device exists](https://github.com/dosentmatter/force-stdin-tty/blob/master/src/index.ts#L11). This device doesn't exist on windows and I think the equivalent is [`CON`](https://github.com/dosentmatter/force-stdin-tty/issues/1).

It might work for Unix shell-like environment on windows, because the `/dev/tty` device should exist. I haven't tested.

This package does the same thing as [opening stdin in the shell](https://stackoverflow.com/a/10015707/7381355). If you are on a Unix shell, you could open stdin with a shell script before running your node script. This package just allows you to write everything in node.

I don't currently have a windows dev environment ready. If you want to help me test, you can edit [`node_modules/force-stdin-tty/lib/index.js`](https://npm.runkit.com/force-stdin-tty/lib/index.js?t=1589565290412) and replace `'/dev/tty'` with `'CON'` and see what happens when running it again.
